### ISSUE TITLE
Define plugin objectives and scope

### ISSUE THREAD

**Issue by cprima** [cprima/jekyll-sketchviz#1]
### Description  
Document the input sources, output formats, required transformations, and configuration options for the Jekyll plugin.

### Acceptance Criteria
- Objectives are documented in a markdown file in the project root.
- Input and output workflows are clearly outlined.
- Configuration options and required transformations are listed.

### Subtasks
- [ ] Identify and document input (collection?) structure and format.
- [x] Define output formats and styling requirements.
- [x] Specify configuration keys and values.

### Dependencies
None.

**Comment by cprima** [comment]
Draft of the features:

## Features

- **Graphviz `.dot` File Support**:
  - Converts `.dot` files into SVG using the `dot` executable.
- **Rough.js Integration**:
  - Adds sketch-style effects to `rect`, `circle`, `ellipse`, `line`, `polygon`, `polyline`, and `path` elements.
- **Output Formats**:
  - **Inline SVGs**: Styled via CSS for webpage inclusion.
  - **Filesystem SVGs**: Unstyled, inheriting Graphviz defaults, ideal for printed or static usage.
- **Customizable Settings**:
  - Configure Rough.js parameters (`roughness`, `bowing`), output directories, and CSS class mappings.
- **Flexible Liquid Tag API**:
  - Include diagrams inline or as files with per-use overrides.
- **Theme-Agnostic Styling**:
  - Inline SVGs styled using global or diagram-specific CSS.

**Comment by cprima** [comment]
WIP `_config.yml`

```YAML
sketchviz:
  input_collection: graphs
  output:
    filesystem:
      directory: assets/graphs
      styled: false
    inline:
      styled: true
      css_classes:
        svg: sketchviz
        background: sketchviz-bg
        node: sketchviz-node
        edge: sketchviz-edge
  executable:
    dot: dot
  roughness: 1.5
  bowing: 1.0
  ```
  
  Needs refinement during development regarding styled true/false.
  Would benefit from (early) user feedback.
