### ISSUE TITLE
Publish plugin to RubyGems

### ISSUE THREAD

**Issue by cprima** [cprima/jekyll-sketchviz#17]
### Description  
Publish the plugin to RubyGems for public distribution.

### Acceptance Criteria
- Plugin is successfully published to RubyGems.
- RubyGems page includes accurate metadata and description.
- Plugin can be installed via `gem install`.

### Subtasks
- [x] Verify RubyGems account setup.
- [x] Publish alpha version of the `.gem` file to RubyGems to reserve the name.
- [ ] Publish the `.gem` file to RubyGems.
- [ ] Test installation from RubyGems.

### Dependencies
#15
