### ISSUE TITLE
Design Configuration Options

### ISSUE THREAD

**Issue by cprima** [cprima/jekyll-sketchviz#2]
### Description  
Define YAML keys for global settings (e.g., `input_collection`, `output.directory`, `roughness`) and their default values in `_config.yml`. Ensure the configuration aligns with plugin objectives.

### Acceptance Criteria
- YAML structure is defined and documented.
- Default values for each key are established.
- Configuration examples are included in the README.

### Subtasks
- [x] Draft YAML configuration structure in `_config.yml`.
- [x] Add configuration documentation to the README.
- [x] Review and validate default values.

### Dependencies
#1

**Comment by cprima** [comment]
@see https://github.com/cprima/jekyll-sketchviz/issues/1#issuecomment-2552902261

```YAML
sketchviz:
  input_collection: graphs
  output:
    filesystem:
      directory: assets/graphs
      styled: false
    inline:
      styled: true
      css_classes:
        svg: sketchviz
        background: sketchviz-bg
        node: sketchviz-node
        edge: sketchviz-edge
  executable:
    dot: dot
  roughness: 1.5
  bowing: 1.0
```
