### ISSUE TITLE
Generate Makefile as Rake Wrapper

### ISSUE THREAD

**Issue by cprima** [cprima/jekyll-sketchviz#20]
#### **Description**
Create a Makefile to simplify common development tasks by wrapping Rake commands.

#### **Acceptance Criteria**
- A `Makefile` exists with tasks for linting, testing, building, and releasing.
- Tasks correctly invoke corresponding Rake commands.

#### **Subtasks**
- [x] Define `make test` to run the test suite.
- [x] Define `make lint` to run RuboCop.
- [x] Define `make build` to build the gem.
- [x] Define `make release` to release the gem.

#### **Dependencies**
None.
