### ISSUE TITLE
Research Necessary Jekyll Hooks

### ISSUE THREAD

**Issue by cprima** [cprima/jekyll-sketchviz#3]
### Description  
Identify Jekyll hooks (`:site`, `:documents`, `:pages`, etc.) to handle `.dot` file detection, SVG generation, and file output during the build process.

### Acceptance Criteria
- A list of Jekyll hooks and their purpose is documented.
- Hooks are mapped to specific plugin functionality.
- Edge cases for hooks are considered and documented.

### Subtasks
- [x] Review Jekyll documentation on hooks.
- [x] Create a list of hooks with descriptions.
- [x] Validate selected hooks with small test cases.

### Dependencies
None.

**Comment by cprima** [comment]
### **1. Generator**
- **Pros**:
  - Best for creating/modifying content during builds.
  - Direct access to collections and site-wide metadata.
  - Ideal for handling nested file structures and output generation.
- **Cons**:
  - Can be complex for large-scale or multi-format processing.
  - Runs on every build, so inefficiency can impact performance.

---

### **2. Converter**
- **Pros**:
  - Simplifies format-specific transformations (e.g., `.dot` to `.svg`).
  - Automatically integrates into Jekyll’s rendering pipeline.
  - Minimal implementation overhead for small transformations.
- **Cons**:
  - Limited to single-file transformations; no access to collections or metadata.
  - Requires input files to match specific extensions.

---

### **3. Tags and Filters**
- **Pros**:
  - Flexible for dynamic content generation during page rendering.
  - Ideal for per-use configuration via Liquid syntax.
  - Lightweight and easy to implement.
- **Cons**:
  - Cannot create or modify physical files (e.g., no SVG file generation).
  - Can increase template complexity for large-scale content.

---

### **4. Hooks**
- **Pros**:
  - Provide fine-grained control over the build lifecycle.
  - Allows pre/post-processing of content at multiple stages.
  - Can complement other extensions like generators or tags.
- **Cons**:
  - Can make debugging complex if multiple hooks are used in tandem.
  - Requires careful planning to avoid performance issues or unintended behavior.

---

### **5. Commands**
- **Pros**:
  - Useful for developer-facing utilities or one-off tasks.
  - Can simplify debugging and manual processing.
  - Allows integration with CLI workflows outside Jekyll’s normal build process.
- **Cons**:
  - Not part of the build pipeline, so cannot automate file generation during builds.
  - Limited scope for user-facing functionality.

---

### **6. Readers**
- **Pros**:
  - Enables customization of how Jekyll reads files and collections.
  - Useful for adding support for custom data formats or processing logic.
- **Cons**:
  - Limited to input handling; cannot directly generate or transform output files.
  - May require additional extensions (e.g., a generator) for complete workflows.

---

### **7. Static File Handlers**
- **Pros**:
  - Allows modification of static files before copying to the output directory.
  - Useful for adding metadata or performing post-write processing.
- **Cons**:
  - Limited to static files; no access to dynamic or template-driven content.
  - Cannot create new content.

---

### **8. Data Processors**
- **Pros**:
  - Excellent for customizing site data loaded from `_data` or collections.
  - Useful for preprocessing data for templates.
- **Cons**:
  - Cannot directly handle file transformations or template rendering.
  - May need additional extensions for end-to-end workflows.

---

### **9. Layouts and Includes Extensions**
- **Pros**:
  - Enhances modularity and reuse of templates.
  - Simplifies complex designs by abstracting reusable components.
- **Cons**:
  - Limited to template-level enhancements; cannot modify content or static files.
  - Requires other extensions (e.g., filters) for dynamic behavior.

**Comment by cprima** [comment]
### **1. Generator**
- **Why**:
  - Generators are ideal for creating or transforming content during the build process, which is essential for converting `.dot` files into SVGs.
  - Provides direct access to collections (`_graphs`) and the ability to generate both inline and filesystem outputs.
  - Allows configuration handling (e.g., output directories, Rough.js parameters).

- **How**:
  - Use the generator to process `.dot` files into SVGs, apply Rough.js transformations, and manage output formats.
  - Output inline SVGs styled via CSS and unstyled filesystem SVGs with Graphviz defaults.

---

### **2. Tags (Liquid API)**
- **Why**:
  - Enables users to include inline SVGs or references to filesystem SVGs in their content via a flexible API.
  - Allows per-use overrides for parameters like `roughness`, `bowing`, and `styled`.

- **How**:
  - Implement a custom Liquid tag (`{% sketchviz %}`) to dynamically include diagrams in pages or posts.
  - Use tag parameters to determine whether to render the SVG inline or reference the generated file.

---

### **3. Hooks (Optional for Fine-Tuning)**
- **Why**:
  - Useful for additional control during the build lifecycle, such as pre- or post-processing the generated SVGs.
  - Allows seamless integration with Jekyll’s rendering pipeline without impacting other plugins or content.

- **How**:
  - Use hooks like `:site, :post_write` to finalize output or log status after processing.
  - Optionally modify generated files (e.g., for caching or validation).

---

### **Recommended Combination**
- **Primary Extension**: **Generator**
  - Core processing of `.dot` files and Rough.js transformations.
  - Manages output to filesystem and inline SVG generation.

- **Supplementary Extensions**:
  1. **Tags**: For user-facing flexibility in content inclusion.
  2. **Hooks**: Optional, for fine-grained control and efficiency improvements.

**Comment by cprima** [comment]
<h3><strong>Tags</strong></h3>
<p>Custom Liquid tags to allow flexible content inclusion.</p>
<h4><strong>1. <code inline="">{% sketchviz %}</code></strong></h4>
<ul>
<li><strong>Purpose</strong>: Include a diagram in a post or page.</li>
<li><strong>Usage</strong>:
<pre><code class="language-liquid">{% sketchviz "diagram.dot" %}
{% sketchviz "diagram.dot", inline: true, roughness: 2.5, styled: true %}
</code></pre>
</li>
<li><strong>Parameters</strong>:
<ul>
<li><code inline="">file</code> (required): Path to the <code inline="">.dot</code> file.</li>
<li><code inline="">inline</code> (optional): Render as inline SVG (<code inline="">true</code> or <code inline="">false</code>).</li>
<li><code inline="">styled</code> (optional): Apply CSS styling (<code inline="">true</code> or <code inline="">false</code>).</li>
<li><code inline="">roughness</code>, <code inline="">bowing</code> (optional): Override global Rough.js settings.</li>
</ul>
</li>
</ul>
<hr>
<h3><strong>Hooks</strong></h3>
<p>Jekyll hooks for lifecycle control and fine-grained customization.</p>
<h4><strong>1. <code inline="">:site, :post_write</code></strong></h4>
<ul>
<li><strong>Purpose</strong>: Finalize or post-process SVGs after they are written to the output directory.</li>
<li><strong>Use Case</strong>:
<ul>
<li>Log the status of SVG generation.</li>
<li>Perform caching or validation checks on generated files.</li>
</ul>
</li>
</ul>
<h4><strong>2. <code inline="">:documents, :post_render</code></strong></h4>
<ul>
<li><strong>Purpose</strong>: Modify inline SVGs right after they are rendered.</li>
<li><strong>Use Case</strong>:
<ul>
<li>Ensure inline SVGs are styled correctly.</li>
<li>Validate the inclusion of required CSS classes.</li>
</ul>
</li>
</ul>
<h4><strong>3. <code inline="">:static_files, :post_write</code></strong></h4>
<ul>
<li><strong>Purpose</strong>: Process or verify filesystem SVGs after they are written to the output directory.</li>
<li><strong>Use Case</strong>:
<ul>
<li>Adjust file metadata or perform integrity checks on SVG outputs.</li>
</ul>
</li>
</ul>
<hr>
<h3><strong>Generator</strong></h3>
<p>A custom generator to handle <code inline="">.dot</code> file detection, SVG generation, and Rough.js transformations.</p>
<h4><strong>Implementation Overview</strong></h4>
<ul>
<li><strong>Input</strong>:
<ul>
<li>Use <code inline="">site.collections["graphs"]</code> to locate <code inline="">.dot</code> files.</li>
</ul>
</li>
<li><strong>Output</strong>:
<ul>
<li>Generate inline SVGs styled with CSS.</li>
<li>Generate unstyled filesystem SVGs inheriting Graphviz defaults.</li>
<li>Apply Rough.js transformations to supported elements (<code inline="">rect</code>, <code inline="">circle</code>, etc.).</li>
</ul>
</li>
<li><strong>Customization</strong>:
<ul>
<li>Respect global settings from <code inline="">_config.yml</code>.</li>
<li>Allow per-file overrides via front matter or Liquid tag parameters.</li>
</ul>
</li>
<li><strong>Caching</strong>:
<ul>
<li>Skip processing for unchanged <code inline="">.dot</code> files by comparing timestamps or checksums.</li>
</ul>
</li>
</ul>
<h4><strong>Core Tasks</strong>:</h4>
<ol>
<li><strong>Detect <code inline="">.dot</code> Files</strong>:
<ul>
<li>Traverse the specified collection and subdirectories.</li>
</ul>
</li>
<li><strong>Generate SVGs</strong>:
<ul>
<li>Invoke the <code inline="">dot</code> executable for conversion.</li>
<li>Apply Rough.js transformations to specified elements.</li>
</ul>
</li>
<li><strong>Output Management</strong>:
<ul>
<li>Write SVGs to the configured filesystem directory.</li>
<li>Embed inline SVGs dynamically if requested.</li>
</ul>
</li>
</ol>
<hr>
<h3>Summary of Responsibilities</h3>

Feature | Tags | Hooks | Generator
-- | -- | -- | --
.dot to SVG Conversion | {% sketchviz %} | - | Core task
Rough.js Integration | {% sketchviz %} params | :documents, :post_render | Apply transformations
Inline SVGs | {% sketchviz %} | :documents, :post_render | Generates and applies styling
Filesystem SVGs | - | :static_files, :post_write | Generates unstyled SVGs
Customizable Settings | {% sketchviz %} params | - | Reads from _config.yml
Theme-Agnostic Styling | {% sketchviz %} | :documents, :post_render | Embeds default styles/classes


<p>This list integrates the plugin's features across Jekyll's extensibility options. </p>

**Comment by cprima** [comment]
### Test in `spec/jekyll_sketchviz/generator_hooks_spec.rb`

#### Registers the `:site, :post_write` Hook:
```ruby
it 'registers the :site, :post_write hook' do
  expect { generator.generate(mock_site) }
    .to change { Jekyll::Hooks.instance_variable_get(:@hooks)[:site][:post_write].size }
    .by(1)
end
```

#### Executes the `:site, :post_write` Hook for Processing:
```ruby
it 'executes the :site, :post_write hook for .dot to .svg processing' do
  generator.generate(mock_site)

  expect(mock_processor).to have_received(:process)
    .with('spec/mock_files/example01.dot', '/mock/site/_site/assets/graphs')
  expect(mock_processor).to have_received(:process)
    .with('spec/mock_files/example02.dot', '/mock/site/_site/assets/graphs')
end
```

### What These Tests Cover:
1. **Hook Registration (`:site, :post_write`)**:
   - Verifies that the plugin properly integrates with Jekyll by registering a hook that triggers after the site build is complete (`:post_write`).
   - Ensures that the hook is tied to the `site` lifecycle event.

2. **Hook Execution**:
   - Validates that the `:post_write` hook processes `.dot` files from the specified collection into `.svg` files.
   - Ensures the `process` method of `GraphvizProcessor` is called for each `.dot` file with the correct input and output paths.
   - Confirms that the plugin respects user configurations, such as output paths and collection names.
