### ISSUE TITLE
Implement `.dot` File Collection Handling

### ISSUE THREAD

**Issue by cprima** [cprima/jekyll-sketchviz#4]
### Description  
Use Jekyll’s collections API to detect `.dot` files in the specified collection. Handle nested folder structures and provide metadata for processing and output.

### Acceptance Criteria
- `.dot` files in the configured collection are detected.
- Nested folder structures in the collection are mirrored in the output directory.
- Metadata for processing and output is accessible.

### Subtasks
- [x] Write code to detect `.dot` files in the collection.
- [x] Implement logic to mirror folder structure in output.
- [x] Ensure output dir is in the directory of the generated site, conventionally _site (but user configurable)
- [x] Make basepath configurable
- [x] Test detection and metadata generation.

### Dependencies
#1 
#3

**Comment by cprima** [comment]
### Test in `spec/jekyll_sketchviz/generator_spec.rb`
```ruby
it 'processes individual .dot files with correct paths' do
  generator.generate(mock_site)
  expect(mock_processor).to have_received(:process)
    .with('spec/mock_files/example01.dot', '/mock/site/_site/assets/graphs')
end
```

### What it Validates:
1. **Input Base Directory**: The test ensures that the `.dot` file is processed relative to the input base directory.
2. **Output Base Directory**: The output directory is checked to be within `site.dest` (e.g., `_site`) and follows the user-configured path for generated assets (`assets/graphs`).

**Comment by cprima** [comment]
### Test in `spec/jekyll_sketchviz/configuration_spec.rb`
```ruby
context 'when a full user configuration is provided' do
  let(:user_config) do
    {
      'output' => {
        'filesystem' => {
          'path' => './custom/output/path'
        }
      }
    }
  end

  it 'overrides the filesystem output path' do
    result = described_class.from_site(site)
    expect(result[:output][:filesystem][:path]).to eq('./custom/output/path')
  end
end
```

### What it Validates:
1. **Default Behavior**: If no user configuration is provided, the `path` defaults to `./assets/graphs`.
2. **Custom Behavior**: If the user specifies a different path in `_config.yml`, the test ensures that the custom path is respected.

**Comment by cprima** [comment]
### Test in `spec/jekyll_sketchviz/configuration_spec.rb`

#### Input Collection Basepath Configuration:
```ruby
context 'when a full user configuration is provided' do
  let(:user_config) do
    {
      'input_collection' => 'custom_graphs'
    }
  end

  it 'overrides the input_collection value' do
    result = described_class.from_site(site)
    expect(result[:input_collection]).to eq('custom_graphs')
  end
end
```

#### Output Basepath Configuration:
```ruby
context 'when a full user configuration is provided' do
  let(:user_config) do
    {
      'output' => {
        'filesystem' => {
          'path' => './custom/output/path'
        }
      }
    }
  end

  it 'overrides the filesystem output path' do
    result = described_class.from_site(site)
    expect(result[:output][:filesystem][:path]).to eq('./custom/output/path')
  end
end
```

### What These Tests Cover:
1. **Input Basepath (`input_collection`)**:
   - Verifies the collection name (`input_collection`) that determines the input folder can be customized via the user configuration.
2. **Output Basepath (`output[:filesystem][:path]`)**:
   - Ensures that the output directory path under the `_site` folder can be customized, respecting user overrides in `_config.yml`.

**Comment by cprima** [comment]
### Problem

**Issue**: The Graphviz `dot` executable fails to process `.dot` files containing Jekyll frontmatter, raising a syntax error. Jekyll, however, requires frontmatter to include files in its collections, creating a conflict between Jekyll's collection system and valid Graphviz input.

**Impact**:
- Files with frontmatter cause build errors during Graphviz processing.
- `.dot` files without frontmatter are excluded from Jekyll collections, preventing them from being processed automatically.
- Users are forced to choose between metadata support and valid `.dot` files, disrupting workflows.

**Root Cause**:
- Jekyll adds files to collections only if they have valid frontmatter, while the Graphviz `dot` tool does not support files with YAML metadata.

**Desired Outcome**:
- Ensure `.dot` files are valid inputs for the `dot` executable while maintaining compatibility with Jekyll’s collection system or providing an alternative handling mechanism.

**Comment by cprima** [comment]
Here are several approaches to address the issue of handling `.dot` files with frontmatter in the JekyllSketchviz plugin. Each approach comes with its pros and cons:

---

### **1. Ignore Frontmatter Requirement for `.dot` Files**
#### Implementation:
- Bypass Jekyll's collection system and directly scan the input directory for `.dot` files.
#### Pros:
- Works seamlessly for `.dot` files without requiring frontmatter.
- Aligns better with how `.dot` files are typically authored.
- Avoids issues with invalid Graphviz syntax caused by frontmatter.
#### Cons:
- Bypassing Jekyll's collection system may complicate integration with other plugins or functionality.
- Custom logic for directory traversal and filtering needs to be implemented.
- Loses the metadata benefits provided by frontmatter.

---

### **2. Strip Frontmatter Before Processing**
#### Implementation:
- Preprocess `.dot` files to remove YAML frontmatter (lines wrapped in `---`).
- Pass only the clean Graphviz content to the `dot` executable.
#### Pros:
- Retains compatibility with Jekyll's collection system.
- Allows `.dot` files to include metadata while ensuring valid Graphviz input.
- Minimal disruption to existing workflows.
#### Cons:
- Extra processing overhead for every `.dot` file.
- Complexity in detecting and correctly removing frontmatter, especially with edge cases (e.g., malformed YAML).
- Could obscure issues if metadata is accidentally misused.

---

### **3.  Define a Custom Jekyll Collection for `.dot` Files**
#### Implementation:
- Create a custom collection in Jekyll that relaxes the frontmatter requirement for `.dot` files.
#### Pros:
- Allows `.dot` files to integrate with Jekyll without metadata or frontmatter.
- Retains full compatibility with Jekyll's collection system.
#### Cons:
- Requires configuration changes in `_config.yml`.
- Might be overkill for simple use cases.

**Comment by cprima** [comment]
The current implementation requires `.dot` files to include frontmatter for inclusion in the Jekyll collection. This requirement stems from Jekyll's behavior, where files must have frontmatter to be recognized as part of collections. However, this introduces friction for users who expect `.dot` files to function without additional metadata.

**Challenges with Frontmatter in `.dot` Files**:
1. **Unintended Errors**: Frontmatter content, even when empty, can interfere with the `dot` executable, leading to syntax errors if not properly stripped.
2. **User Experience**: Expecting users to add frontmatter to every `.dot` file can be seen as counterintuitive, given that `.dot` files are typically standalone.

**Potential Solutions**:
1. **Preprocessing `.dot` Files**: The plugin can strip frontmatter before passing the content to `dot`. This ensures compatibility while adhering to Jekyll's collection requirements.
2. **Custom Collection Handling**: Introduce a custom Jekyll hook or alternative mechanism to include `.dot` files in collections without requiring frontmatter.
3. **Documentation**: Clearly document the requirement for frontmatter and provide examples of minimal valid frontmatter (`---\n---\n`) to avoid confusion.

Given the current architecture, **stripping frontmatter is the most straightforward solution**, but this may require revisiting the handling of edge cases (e.g., single-line frontmatter). If frontmatter handling becomes overly complex, reevaluating the need for it entirely may be warranted.
