### ISSUE TITLE
Develop Liquid Tag for Inline SVGs

### ISSUE THREAD

**Issue by cprima** [cprima/jekyll-sketchviz#9]
### Description  
Create a Liquid tag to embed diagrams as inline SVGs or reference filesystem SVGs. Allow per-use configuration overrides.

```markdown
{% sketchviz "diagram.dot" %}
{% sketchviz "diagram.dot", roughness: 2.5, bowing: 2.0, styled: true %} 
```

### Acceptance Criteria
- Liquid tag supports basic and advanced syntax.
- Inline SVGs are embedded in webpages.
- Filesystem SVGs are referenced via `<img>` tags.

### Subtasks
- [x] Develop the basic `{% sketchviz %}` Liquid tag.
- [x] Support overrides for `inline`, `roughness`, and `styled` parameters.
- [x] Test Liquid tag with various configurations.
- [ ] Inline SVGs are embedded in webpages

### Dependencies
#8
